import { chromium, expect } from '@playwright/test'
import { mkdirSync } from 'node:fs'
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } })
const errors = []
page.on('pageerror', error => errors.push(String(error)))
try {
  await page.goto('http://127.0.0.1:4393/e2e/lab-rules/index.html')
  await page.getByRole('button', { name: '工程规则', exact: true }).click()
  await page.locator('.el-select').first().click()
  await page.getByRole('option').filter({ hasText: '平台' }).first().click()
  await page.getByRole('button', { name: '复制为工程草稿', exact: true }).waitFor()
  await expect(page.getByLabel('审查项目', { exact: true })).toBeDisabled()
  await page.locator('.el-select').first().click()
  await page.getByRole('option', { name: '新建工程草稿', exact: true }).click()
  await page.getByLabel('审查项目', { exact: true }).fill('浏览器验收：厚度条件')
  await page.getByLabel('判断依据与要求', { exact: true }).fill('仅作本地示例试跑，厚度至少 10 mm')
  await page.getByRole('button', { name: '添加判定条件', exact: true }).click()
  await page.getByPlaceholder('例如：thickness', { exact: true }).fill('thickness')
  await page.locator('.condition-expression .el-select').nth(0).click()
  await page.getByRole('option', { name: '大于或等于', exact: true }).click()
  await page.locator('.condition-expression .el-select').nth(1).click()
  await page.getByRole('option', { name: '数字', exact: true }).click()
  await page.getByLabel('比较值 1', { exact: true }).fill('10')
  await page.getByPlaceholder('例如：mm；与事实数据的单位一致').fill('mm')
  const savedResponse = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/rules/versions'))
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  const saved = (await (await savedResponse).json()).data.rule
  if (saved.executionConditions.checks[0].expected !== 10) throw new Error('Saved numeric value mismatch')
  await page.getByRole('heading', { name: '草稿试跑', exact: true }).waitFor()
  const fact = page.locator('.trial-fact')
  await fact.locator('input').nth(0).fill('9')
  await fact.locator('input').nth(2).fill('EXAMPLE-ONLY-1')
  await page.getByRole('button', { name: '运行草稿试跑', exact: true }).click()
  await expect(page.locator('.rule-trial [role="status"]')).toContainText('thickness：不符合')
  await fact.locator('input').nth(0).fill('11')
  await expect(page.locator('.rule-trial [role="status"]')).toHaveCount(0)
  await page.getByRole('button', { name: '运行草稿试跑', exact: true }).click()
  await expect(page.locator('.rule-trial [role="status"]')).toContainText('thickness：符合')
  await expect(page.locator('.rule-trial .el-tag')).toHaveText('符合')
  await expect(page.locator('.rule-trial .el-tag')).toBeVisible()
  mkdirSync('../docs/lab/verification/browser', { recursive: true })
  await page.locator('.rule-trial').screenshot({ path: '../docs/lab/verification/browser/rule-trial-pass.png', animations: 'disabled' })
  await fact.locator('input').nth(2).fill('')
  await page.getByRole('button', { name: '运行草稿试跑', exact: true }).click()
  await expect(page.locator('.rule-trial [role="status"]')).toContainText('thickness：证据不足')
  await page.getByLabel('判断依据与要求', { exact: true }).fill('未保存的修改')
  await expect(page.getByRole('button', { name: '运行草稿试跑', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  await expect(page.getByLabel('判断依据与要求', { exact: true })).toHaveValue('未保存的修改')
  if (errors.length) throw new Error(errors.join('\n'))
  console.log('PASS: readonly, create, numeric conditions, save, fail/pass/missing-evidence trials, stale-result clearing, unsaved-change guard; no browser runtime errors')
} finally { await browser.close() }
