"""Explicit binding corrections not expressible by the legacy rule-profile heuristics.

Maintained source for generation; never reads the generated YAML at runtime.
"""

ATOMIC_BINDING_OVERRIDES = {'AC-R01-03': {'requiredFacts': ['certificateFacts.certificates',
                                 'designLicense.validFrom',
                                 'designLicense.validUntil',
                                 'project.constructionStart',
                                 'project.plannedConstructionEnd',
                                 'project.actualConstructionEnd',
                                 'project.changeClarificationEnd'],
               'tools': ['extract_document_fields',
                         'check_date_covers',
                         'check_certificate_validity',
                         'validate_evidence_grounding']},
 'AC-R02-02': {'requiredFacts': ['certificateFacts.certificates',
                                 'installationLicense.validFrom',
                                 'installationLicense.validUntil',
                                 'project.constructionStart',
                                 'project.plannedConstructionEnd'],
               'tools': ['extract_document_fields',
                         'check_date_covers',
                         'check_certificate_validity',
                         'validate_evidence_grounding']},
 'AC-R03-03': {'requiredFacts': ['certificateFacts.certificates',
                                 'ndtAgencies.agencies[].agencyId',
                                 'ndtAgencies.agencies[].validFrom',
                                 'ndtAgencies.agencies[].validUntil',
                                 'ndtAgencies.agencies[].periodStart',
                                 'ndtAgencies.agencies[].plannedPeriodEnd'],
               'tools': ['extract_document_fields',
                         'check_certificate_validity',
                         'evaluate_ndt_agencies',
                         'validate_evidence_grounding']},
 'AC-R05-01': {'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'evaluate_drawing_review_witness',
                         'validate_evidence_grounding'],
               'parameters': {'profile': 'drawing_review_witness',
                              'clauseSource': 'frozen_standard_clause_package',
                              'failurePolicy': 'business_rule_result',
                              'acceptedTypes': ['review_approval_certificate',
                                                'review_opinion',
                                                'design_reply',
                                                'owner_filing_receipt'],
                              'requireSeal': True,
                              'ruleVersion': 'r05-drawing-review-witness-v1'}},
 'AC-R08-01': {'requiredFacts': ['design.standardReferences',
                                 'standardCatalog.versionStatus',
                                 'officialStandardStatus',
                                 'reviewDate'],
               'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'check_date_covers',
                         'lookup_standard_status',
                         'check_standard_version_active',
                         'validate_evidence_grounding']},
 'AC-R12-01': {'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'extract_table_records',
                         'recognize_signatures_and_seals',
                         'check_signature_completeness',
                         'check_cross_document_match',
                         'check_scope_coverage',
                         'evaluate_component_manufacturer_scope',
                         'validate_evidence_grounding',
                         'verify_org_license']},
 'AC-R24-01': {'requiredFacts': ['certificateFacts.certificates',
                                 'r24.certificates',
                                 'r24.qualificationCodes',
                                 'r24.workDate'],
               'tools': ['extract_welder_certificate',
                         'decode_welder_qualification',
                         'check_welder_work_coverage',
                         'check_certificate_validity',
                         'verify_welder_on_platform']},
 'AC-R35-01': {'requiredFacts': ['r35.projectId',
                                 'r35.organizationId',
                                 'r35.activityDate',
                                 'r35.applicability',
                                 'r35.manual',
                                 'r35.controlledForms',
                                 'r35.appointments',
                                 'r35.implementationRecords',
                                 'r35.equipmentIds',
                                 'r35.calibrationReports'],
               'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'extract_table_records',
                         'evaluate_ndt_quality_system',
                         'validate_evidence_grounding'],
               'parameters': {'decisionTool': 'evaluate_ndt_quality_system',
                              'profile': 'ndt_quality_system',
                              'clauseSource': 'frozen_standard_clause_package',
                              'failurePolicy': 'business_rule_result'}},
 'AC-R35-02': {'parameters': {'resultRole': 'evidence_gate',
                              'minConfidence': 0.75,
                              'requirePage': True,
                              'requireBboxOrQuotedText': True,
                              'denyOnConflict': True}},
 'AC-R38-01': {'requiredFacts': ['certificateFacts.certificates',
                                 'ndtPersonnel.roster',
                                 'ndtPersonnel.qualificationCodes',
                                 'ndtPersonnel.registration',
                                 'actualNdt.workItems'],
               'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'extract_table_records',
                         'check_required',
                         'check_conditional_requirement',
                         'check_ndt_personnel_coverage',
                         'check_certificate_validity',
                         'validate_evidence_grounding']},
 'AC-R36-01': {'requiredFacts': ['r36.projectId', 'r36.applicability', 'r36.plan', 'r36.requirements'],
               'tools': ['get_document_ocr_result',
                         'extract_document_fields',
                         'extract_table_records',
                         'evaluate_r36_ndt_plan',
                         'validate_evidence_grounding'],
               'parameters': {'profile': 'ndt_plan',
                              'decisionTool': 'evaluate_r36_ndt_plan',
                              'clauseSource': 'frozen_standard_clause_package',
                              'failurePolicy': 'business_rule_result'}},
 'AC-R36-02': {'parameters': {'resultRole': 'evidence_gate',
                              'minConfidence': 0.75,
                              'requirePage': True,
                              'requireBboxOrQuotedText': True,
                              'denyOnConflict': True}}}
