from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.ocr_100_collection_intake_verify import (
    is_placeholder,
    resolve_manifest_path,
    verify_collection_intake,
)
from scripts.ocr_100_corpus import SCENARIO_PROFILE_DEFAULTS
from scripts.ocr_100_ingest_samples import SUPPORTED_SUFFIXES, is_likely_standard_doc
from scripts.ocr_eval_set import write_text_file

IGNORED_FILENAMES = {"README.md", ".gitkeep", ".DS_Store"}


def main() -> int:
    parser = argparse.ArgumentParser(description="Auto-fill OCR 100 intake manifest fileName slots from scenario folders.")
    parser.add_argument("intake_dir", help="Directory generated by ocr_100_collection_intake.py.")
    parser.add_argument("--manifest", default="manifest_template.json", help="Manifest path, relative to intake_dir unless absolute.")
    parser.add_argument("--output-manifest", help="Output manifest path. Defaults to manifest_autofilled.json beside the manifest.")
    parser.add_argument("--in-place", action="store_true", help="Overwrite the input manifest instead of writing manifest_autofilled.json.")
    parser.add_argument("--include-standards", action="store_true", help="Allow likely standards/specification PDFs. Default skips them.")
    parser.add_argument("--replace-existing", action="store_true", help="Replace non-placeholder fileName values too.")
    parser.add_argument("--output", help="Optional JSON report path.")
    parser.add_argument("--markdown-output", help="Optional Markdown report path.")
    args = parser.parse_args()

    report = autofill_collection_intake(
        Path(args.intake_dir),
        manifest=Path(args.manifest),
        output_manifest=Path(args.output_manifest) if args.output_manifest else None,
        in_place=bool(args.in_place),
        include_standards=bool(args.include_standards),
        replace_existing=bool(args.replace_existing),
    )
    if args.output:
        write_text_file(Path(args.output), json.dumps(report, ensure_ascii=False, indent=2))
    if args.markdown_output:
        write_text_file(Path(args.markdown_output), markdown_report(report))
    print(json.dumps(report["summary"], ensure_ascii=False, indent=2))
    return 0 if report.get("ok") else 1


def autofill_collection_intake(
    intake_dir: Path,
    *,
    manifest: Path | None = None,
    output_manifest: Path | None = None,
    in_place: bool = False,
    include_standards: bool = False,
    replace_existing: bool = False,
) -> dict[str, Any]:
    intake_dir = intake_dir.expanduser().resolve()
    manifest_path = resolve_manifest_path(intake_dir, manifest or Path("manifest_template.json"))
    failures: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []
    if not manifest_path.exists():
        failures.append(issue("MANIFEST_MISSING", f"Manifest does not exist: {manifest_path}"))
        return build_report(intake_dir, manifest_path, output_manifest or manifest_path, {}, [], failures, warnings, None)
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        failures.append(issue("MANIFEST_INVALID_JSON", f"Manifest is not valid JSON: {exc}"))
        return build_report(intake_dir, manifest_path, output_manifest or manifest_path, {}, [], failures, warnings, None)
    samples = payload.get("samples") if isinstance(payload, dict) else payload
    if not isinstance(samples, list):
        failures.append(issue("MANIFEST_SAMPLES_INVALID", "Manifest must be an object with samples[] or a raw samples array."))
        return build_report(intake_dir, manifest_path, output_manifest or manifest_path, {}, [], failures, warnings, None)

    sample_items = [item for item in samples if isinstance(item, dict)]
    scenario_files = discover_files_by_scenario(intake_dir, sample_items, include_standards=include_standards, warnings=warnings)
    assigned: list[dict[str, Any]] = []
    used_files: set[Path] = existing_file_paths(intake_dir, sample_items) if not replace_existing else set()
    by_scenario_slots = group_slot_indexes(sample_items, replace_existing=replace_existing)
    for scenario, slot_indexes in by_scenario_slots.items():
        available_files = [path for path in scenario_files.get(scenario, []) if path not in used_files]
        if len(available_files) > len(slot_indexes):
            warnings.append(
                issue(
                    "EXTRA_FILES_UNASSIGNED",
                    f"{scenario} has {len(available_files) - len(slot_indexes)} more file(s) than fillable manifest slot(s).",
                    scenario=scenario,
                )
            )
        for slot_index, source_path in zip(slot_indexes, available_files):
            item = sample_items[slot_index]
            old_name = str(item.get("fileName") or "")
            item["fileName"] = source_path.name
            item["autoFilledAt"] = datetime.now(UTC).isoformat()
            item["autoFilledFrom"] = str(source_path)
            used_files.add(source_path)
            assigned.append(
                {
                    "slotId": item.get("slotId"),
                    "scenario": scenario,
                    "oldFileName": old_name,
                    "fileName": source_path.name,
                    "path": str(source_path),
                }
            )
    if failures:
        output_path = None
    else:
        output_path = output_path_for(manifest_path, output_manifest=output_manifest, in_place=in_place)
        if isinstance(payload, dict):
            payload["autoFilledAt"] = datetime.now(UTC).isoformat()
            payload["autoFillSourceManifest"] = str(manifest_path)
        write_text_file(output_path, json.dumps(payload, ensure_ascii=False, indent=2))

    verification = verify_collection_intake(intake_dir, manifest=output_path or manifest_path) if output_path else None
    return build_report(intake_dir, manifest_path, output_path, scenario_files, assigned, failures, warnings, verification)


def output_path_for(manifest_path: Path, *, output_manifest: Path | None, in_place: bool) -> Path:
    if in_place:
        return manifest_path
    if output_manifest:
        output_manifest = output_manifest.expanduser()
        if output_manifest.is_absolute():
            return output_manifest.resolve()
        return (manifest_path.parent / output_manifest).resolve()
    return manifest_path.with_name("manifest_autofilled.json")


def discover_files_by_scenario(
    intake_dir: Path,
    samples: list[dict[str, Any]],
    *,
    include_standards: bool,
    warnings: list[dict[str, Any]],
) -> dict[str, list[Path]]:
    scenario_dirs: dict[str, Path] = {}
    for item in samples:
        scenario = str(item.get("scenario") or "")
        drop_directory = str(item.get("dropDirectory") or "")
        if scenario not in SCENARIO_PROFILE_DEFAULTS or scenario in scenario_dirs or not drop_directory:
            continue
        directory = resolve_inside_intake(intake_dir, drop_directory)
        if directory is not None:
            scenario_dirs[scenario] = directory
    result: dict[str, list[Path]] = {}
    for scenario, directory in scenario_dirs.items():
        files: list[Path] = []
        if not directory.is_dir():
            result[scenario] = files
            continue
        for item in sorted(path for path in directory.iterdir() if path.is_file()):
            if item.name in IGNORED_FILENAMES or item.name.startswith("."):
                continue
            if item.suffix.lower() not in SUPPORTED_SUFFIXES:
                warnings.append(issue("UNSUPPORTED_FILE_SKIPPED", f"Skipped unsupported file: {item}", scenario=scenario))
                continue
            if not include_standards and is_likely_standard_doc(item):
                warnings.append(issue("STANDARD_LIKE_FILE_SKIPPED", f"Skipped likely standards/specification file: {item}", scenario=scenario))
                continue
            files.append(item.resolve())
        result[scenario] = files
    return result


def resolve_inside_intake(intake_dir: Path, value: str) -> Path | None:
    path = Path(value).expanduser()
    candidate = path if path.is_absolute() else intake_dir / path
    try:
        resolved = candidate.resolve()
        resolved.relative_to(intake_dir)
        return resolved
    except Exception:
        return None


def existing_file_paths(intake_dir: Path, samples: list[dict[str, Any]]) -> set[Path]:
    paths: set[Path] = set()
    for item in samples:
        file_name = str(item.get("fileName") or "")
        drop_directory = str(item.get("dropDirectory") or "")
        if not file_name or is_placeholder(file_name) or Path(file_name).name != file_name:
            continue
        directory = resolve_inside_intake(intake_dir, drop_directory)
        if directory is not None:
            paths.add((directory / file_name).resolve())
    return paths


def group_slot_indexes(samples: list[dict[str, Any]], *, replace_existing: bool) -> dict[str, list[int]]:
    grouped: dict[str, list[int]] = {}
    for index, item in enumerate(samples):
        scenario = str(item.get("scenario") or "")
        if scenario not in SCENARIO_PROFILE_DEFAULTS:
            continue
        file_name = str(item.get("fileName") or "")
        if not replace_existing and file_name and not is_placeholder(file_name):
            continue
        grouped.setdefault(scenario, []).append(index)
    return grouped


def build_report(
    intake_dir: Path,
    manifest_path: Path,
    output_path: Path | None,
    scenario_files: dict[str, list[Path]],
    assigned: list[dict[str, Any]],
    failures: list[dict[str, Any]],
    warnings: list[dict[str, Any]],
    verification: dict[str, Any] | None,
) -> dict[str, Any]:
    scenario_file_counts = {scenario: len(paths) for scenario, paths in sorted(scenario_files.items())}
    verification_summary = verification.get("summary") if isinstance(verification, dict) and isinstance(verification.get("summary"), dict) else {}
    summary = {
        "schemaVersion": "aicheck-ocr-100-collection-intake-autofill-v1",
        "generatedAt": datetime.now(UTC).isoformat(),
        "intakeDir": str(intake_dir),
        "manifest": str(manifest_path),
        "outputManifest": str(output_path) if output_path else None,
        "assignedSlots": len(assigned),
        "discoveredFiles": sum(scenario_file_counts.values()),
        "scenarioFileCounts": scenario_file_counts,
        "readyToIngest": bool(verification.get("readyToIngest")) if isinstance(verification, dict) else False,
        "remainingPlaceholders": verification_summary.get("placeholderSlots"),
        "verificationFailureCount": verification_summary.get("failureCount"),
        "verificationWarningCount": verification_summary.get("warningCount"),
        "failureCount": len(failures),
        "warningCount": len(warnings),
        "failureCounts": count_codes(failures),
        "warningCounts": count_codes(warnings),
    }
    return {
        "schemaVersion": "aicheck-ocr-100-collection-intake-autofill-v1",
        "ok": not failures,
        "summary": summary,
        "assigned": assigned,
        "failures": failures,
        "warnings": warnings,
        "verification": verification,
    }


def issue(code: str, message: str, **extra: Any) -> dict[str, Any]:
    payload = {"code": code, "message": message}
    payload.update({key: value for key, value in extra.items() if value not in {None, ""}})
    return payload


def count_codes(items: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        code = str(item.get("code") or "UNKNOWN")
        counts[code] = counts.get(code, 0) + 1
    return dict(sorted(counts.items()))


def markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    lines = [
        "# OCR 100 Collection Intake Autofill",
        "",
        f"- Status: {'READY' if summary.get('readyToIngest') else 'NOT READY'}",
        f"- Assigned slots: {summary.get('assignedSlots', 0)}",
        f"- Discovered files: {summary.get('discoveredFiles', 0)}",
        f"- Remaining placeholders: {summary.get('remainingPlaceholders')}",
        f"- Output manifest: {summary.get('outputManifest')}",
        "",
        "## Scenario Files",
        "",
        "| Scenario | Files |",
        "| --- | ---: |",
    ]
    for scenario, count in (summary.get("scenarioFileCounts") or {}).items():
        lines.append(f"| {scenario} | {count} |")
    if not summary.get("scenarioFileCounts"):
        lines.append("| none | 0 |")
    lines.extend(["", "## Assigned Slots", ""])
    assigned = report.get("assigned") if isinstance(report.get("assigned"), list) else []
    if assigned:
        lines.extend(["| Slot | Scenario | File |", "| --- | --- | --- |"])
        for item in assigned:
            if isinstance(item, dict):
                lines.append(f"| {item.get('slotId')} | {item.get('scenario')} | {item.get('fileName')} |")
    else:
        lines.append("No slots assigned.")
    lines.extend(["", "## Warnings", ""])
    warnings = report.get("warnings") if isinstance(report.get("warnings"), list) else []
    if warnings:
        lines.extend(["| Code | Scenario | Message |", "| --- | --- | --- |"])
        for item in warnings:
            if isinstance(item, dict):
                lines.append(f"| {item.get('code')} | {item.get('scenario', '')} | {item.get('message')} |")
    else:
        lines.append("No warnings.")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
