from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from pathlib import Path
from types import SimpleNamespace
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.ocr_eval_set import write_text_file
from scripts.ocr_sample_probe import (
    allow_probe_source_dir,
    apply_auto_discovered_runtime,
    attach_gate_failures,
    build_summary,
    collect_gate_failures,
    count_values,
)

ParseRunner = Callable[[Path, dict[str, Any], dict[str, Any]], dict[str, Any]]


def main() -> int:
    parser = argparse.ArgumentParser(description="Run OCR sample probes for an OCR 100 sample queue.")
    parser.add_argument("queue", help="Sample queue JSON generated by ocr_100_ingest_samples.py.")
    parser.add_argument("--base-dir", default=str(Path(__file__).resolve().parents[2]), help="Base directory for relative source.path values.")
    parser.add_argument("--output", help="Combined sample-summary JSON output path. This file can be passed to ocr_100_scorecard.py --sample-summary.")
    parser.add_argument("--summary-dir", help="Optional directory for per-case summary JSON files.")
    parser.add_argument("--limit", type=int, help="Maximum number of cases to probe.")
    parser.add_argument("--case-id", action="append", default=[], help="Probe only matching caseId. Repeatable.")
    parser.add_argument("--scenario", action="append", default=[], help="Probe only matching scenario. Repeatable.")
    parser.add_argument("--auto-discover-runtime", action="store_true", help="Apply runtime-doctor recommended local OCR Python/model paths.")
    parser.add_argument("--disable-result-cache", action="store_true", help="Bypass full parse-result cache.")
    parser.add_argument("--disable-engine-cache", action="store_true", help="Bypass per-engine raw result cache.")
    parser.add_argument("--disable-variant-cache", action="store_true", help="Bypass generated preprocess variant cache.")
    parser.add_argument("--run-all-variants", action="store_true", help="Route every generated candidate image through eligible engines.")
    parser.add_argument(
        "--scorecard-sample-gate",
        action="store_true",
        help="Apply the OCR 100 real sample probe gate to each item.",
    )
    parser.add_argument("--require-all-pass", action="store_true", help="Exit non-zero when any probed item fails its gate.")
    args = parser.parse_args()
    apply_auto_discovered_runtime(args)

    report = build_probe_batch_report(
        Path(args.queue),
        base_dir=Path(args.base_dir),
        output_dir=Path(args.summary_dir) if args.summary_dir else None,
        limit=args.limit,
        case_ids=set(args.case_id or []),
        scenarios=set(args.scenario or []),
        options=parse_options_from_args(args),
        scorecard_sample_gate=bool(args.scorecard_sample_gate),
    )
    if args.output:
        write_text_file(Path(args.output), json.dumps(report, ensure_ascii=False, indent=2))
    print(json.dumps(report["summary"], ensure_ascii=False, indent=2))
    return 1 if args.require_all_pass and not report["summary"]["gatePassed"] else 0


def build_probe_batch_report(
    queue_path: Path,
    *,
    base_dir: Path,
    output_dir: Path | None = None,
    limit: int | None = None,
    case_ids: set[str] | None = None,
    scenarios: set[str] | None = None,
    options: dict[str, Any] | None = None,
    scorecard_sample_gate: bool = False,
    parse_runner: ParseRunner | None = None,
) -> dict[str, Any]:
    payload = json.loads(queue_path.read_text(encoding="utf-8"))
    cases = payload.get("cases") if isinstance(payload, dict) else payload
    if not isinstance(cases, list):
        raise ValueError("sample queue must be a JSON object with cases[] or a raw array")
    selected = select_cases(cases, case_ids=case_ids or set(), scenarios=scenarios or set())
    if limit is not None:
        selected = selected[: max(0, int(limit))]
    output_dir.mkdir(parents=True, exist_ok=True) if output_dir else None

    items: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []
    for case in selected:
        item = probe_case(
            case,
            queue_path=queue_path,
            base_dir=base_dir,
            options=options or {},
            scorecard_sample_gate=scorecard_sample_gate,
            parse_runner=parse_runner,
        )
        items.append(item)
        failures.extend(item.get("gateFailures") or [])
        if output_dir:
            write_text_file(output_dir / f"{safe_case_id(str(item.get('caseId') or len(items)))}.json", json.dumps(item, ensure_ascii=False, indent=2))
    summary = {
        "schemaVersion": "aicheck-ocr-100-sample-probe-batch-v1",
        "queue": str(queue_path),
        "cases": len(selected),
        "passed": len([item for item in items if item.get("gatePassed")]),
        "failed": len([item for item in items if not item.get("gatePassed")]),
        "gatePassed": not failures,
        "gateFailureCounts": count_values(failure.get("code") for failure in failures),
        "scenarioCounts": count_values(item.get("scenario") for item in items),
        "qualityStatuses": sorted({str(item.get("qualityStatus")) for item in items}),
        "outputDir": str(output_dir) if output_dir else None,
    }
    return {
        "schemaVersion": "aicheck-ocr-100-sample-probe-batch-report-v1",
        "summary": summary,
        "items": items,
    }


def select_cases(cases: list[Any], *, case_ids: set[str], scenarios: set[str]) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for case in cases:
        if not isinstance(case, dict):
            continue
        case_id = str(case.get("caseId") or "")
        scenario = str(case.get("scenario") or "")
        if case_ids and case_id not in case_ids:
            continue
        if scenarios and scenario not in scenarios:
            continue
        selected.append(case)
    return selected


def probe_case(
    case: dict[str, Any],
    *,
    queue_path: Path,
    base_dir: Path,
    options: dict[str, Any],
    scorecard_sample_gate: bool,
    parse_runner: ParseRunner | None = None,
) -> dict[str, Any]:
    source = resolve_case_source(case, queue_path=queue_path, base_dir=base_dir)
    parse_options = dict(case.get("options") if isinstance(case.get("options"), dict) else {})
    parse_options.update(options)
    if parse_runner is None:
        parse_runner = run_local_ocr
    result = parse_runner(source, case, parse_options)
    summary = build_summary(result, source=str(source))
    summary["caseId"] = case.get("caseId")
    summary["scenario"] = case.get("scenario")
    summary["profileId"] = result.get("profileId") or case.get("profileId")
    summary["documentType"] = result.get("documentType") or case.get("documentType")
    gate_args = scorecard_gate_args() if scorecard_sample_gate else basic_gate_args()
    failures = collect_gate_failures([summary], gate_args)
    attach_gate_failures(summary, failures)
    return summary


def run_local_ocr(source: Path, case: dict[str, Any], options: dict[str, Any]) -> dict[str, Any]:
    allow_probe_source_dir(source)
    from apps.ocr_service.service import ocr_service

    return ocr_service.parse_document(
        str(source),
        file_name=(case.get("source") or {}).get("fileName") if isinstance(case.get("source"), dict) else source.name,
        profile_id=case.get("profileId"),
        document_type=case.get("documentType"),
        options=options,
    )


def resolve_case_source(case: dict[str, Any], *, queue_path: Path, base_dir: Path) -> Path:
    source = case.get("source")
    raw_path = source.get("path") if isinstance(source, dict) else source
    path = Path(str(raw_path or "")).expanduser()
    if path.is_absolute():
        return path
    candidates = [
        (base_dir / path).resolve(),
        (queue_path.parent / path).resolve(),
        (Path.cwd() / path).resolve(),
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def parse_options_from_args(args: argparse.Namespace) -> dict[str, Any]:
    options: dict[str, Any] = {}
    if bool(getattr(args, "disable_result_cache", False)):
        options["disableResultCache"] = True
    if bool(getattr(args, "disable_engine_cache", False)):
        options["disableEngineResultCache"] = True
    if bool(getattr(args, "disable_variant_cache", False)):
        options["disableVariantCache"] = True
    if bool(getattr(args, "run_all_variants", False)):
        options["runAllVariants"] = True
    return options


def basic_gate_args() -> argparse.Namespace:
    return gate_args()


def scorecard_gate_args() -> argparse.Namespace:
    return gate_args(
        min_fields=5,
        min_formal_tables=1,
        min_business_rows=5,
        min_readable_seals=1,
        min_fragment_seals=1,
        max_missing_expected_seal_types=0,
        min_evidence_completeness=0.95,
        require_quality_status="auto_usable",
    )


def gate_args(**overrides: Any) -> argparse.Namespace:
    defaults = {
        "min_fragments": 1,
        "min_fields": 0,
        "require_field_code": [],
        "max_field_conflicts": None,
        "max_missing_required_fields": None,
        "min_tables": 0,
        "min_formal_tables": None,
        "min_business_rows": None,
        "max_heuristic_tables": None,
        "max_table_review_required": None,
        "max_missing_required_tables": None,
        "min_seals": 0,
        "min_readable_seals": None,
        "min_fragment_seals": None,
        "require_seal_type": [],
        "max_missing_expected_seal_types": None,
        "max_seal_review_required": None,
        "min_engine_cache_hit_rate": None,
        "max_engine_duration_ms": None,
        "max_single_engine_duration_ms": None,
        "fail_on_engine_failure": False,
        "min_evidence_completeness": None,
        "max_low_confidence_fields": None,
        "max_missing_evidence": None,
        "require_quality_status": None,
    }
    defaults.update(overrides)
    return SimpleNamespace(**defaults)


def safe_case_id(value: str) -> str:
    safe = "".join(char if char.isalnum() or char in {"-", "_", "."} else "-" for char in value.strip())
    return safe or "case"


if __name__ == "__main__":
    raise SystemExit(main())
