from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.ocr_100_corpus import SCENARIO_PROFILE_DEFAULTS
from scripts.ocr_100_ingest_samples import SUPPORTED_SUFFIXES
from scripts.ocr_eval_set import write_text_file


PLACEHOLDER_PREFIX = "replace-with-"


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify an OCR 100 sample intake package before ingesting local files.")
    parser.add_argument("intake_dir", help="Directory generated by ocr_100_collection_intake.py.")
    parser.add_argument("--manifest", default="manifest_template.json", help="Manifest path, relative to intake_dir unless absolute.")
    parser.add_argument("--output", help="Optional JSON report path.")
    parser.add_argument("--markdown-output", help="Optional Markdown report path.")
    parser.add_argument("--strict", action="store_true", help="Return non-zero unless every slot references an existing ingestable file.")
    args = parser.parse_args()

    report = verify_collection_intake(Path(args.intake_dir), manifest=Path(args.manifest))
    if args.output:
        write_text_file(Path(args.output), json.dumps(report, ensure_ascii=False, indent=2))
    if args.markdown_output:
        write_text_file(Path(args.markdown_output), markdown_report(report))
    print(json.dumps(report["summary"], ensure_ascii=False, indent=2))
    if args.strict:
        return 0 if report.get("readyToIngest") else 1
    return 0 if report.get("ok") else 1


def verify_collection_intake(intake_dir: Path, *, manifest: Path | None = None) -> dict[str, Any]:
    intake_dir = intake_dir.expanduser().resolve()
    manifest_path = resolve_manifest_path(intake_dir, manifest or Path("manifest_template.json"))
    failures: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    if not intake_dir.exists() or not intake_dir.is_dir():
        failures.append(issue("INTAKE_DIR_MISSING", f"Intake directory does not exist: {intake_dir}"))
        return build_report(intake_dir, manifest_path, [], failures, warnings, {})
    for required_name in ["README.md", "commands.json", "summary.json"]:
        if not (intake_dir / required_name).exists():
            warnings.append(issue("INTAKE_SUPPORT_FILE_MISSING", f"Missing support file: {required_name}"))
    payload: dict[str, Any] = {}
    samples: list[Any] = []
    if not manifest_path.exists():
        failures.append(issue("MANIFEST_MISSING", f"Manifest does not exist: {manifest_path}"))
        return build_report(intake_dir, manifest_path, [], failures, warnings, {})
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        failures.append(issue("MANIFEST_INVALID_JSON", f"Manifest is not valid JSON: {exc}"))
        return build_report(intake_dir, manifest_path, [], failures, warnings, {})
    raw_samples = payload.get("samples") if isinstance(payload, dict) else payload
    if not isinstance(raw_samples, list):
        failures.append(issue("MANIFEST_SAMPLES_INVALID", "Manifest must be an object with samples[] or a raw samples array."))
        return build_report(intake_dir, manifest_path, [], failures, warnings, {})
    samples = raw_samples

    summary = load_summary(intake_dir)
    verify_summary_directories(intake_dir, summary, failures, warnings)
    verify_manifest_samples(intake_dir, samples, failures, warnings)
    return build_report(intake_dir, manifest_path, samples, failures, warnings, summary)


def resolve_manifest_path(intake_dir: Path, manifest: Path) -> Path:
    manifest = manifest.expanduser()
    if manifest.is_absolute():
        return manifest.resolve()
    return (intake_dir / manifest).resolve()


def load_summary(intake_dir: Path) -> dict[str, Any]:
    summary_path = intake_dir / "summary.json"
    if not summary_path.exists():
        return {}
    try:
        payload = json.loads(summary_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def verify_summary_directories(
    intake_dir: Path,
    summary: dict[str, Any],
    failures: list[dict[str, Any]],
    warnings: list[dict[str, Any]],
) -> None:
    scenario_items = summary.get("scenarioItems") if isinstance(summary.get("scenarioItems"), list) else []
    for item in scenario_items:
        if not isinstance(item, dict):
            continue
        scenario = str(item.get("scenario") or "")
        drop_directory = str(item.get("dropDirectory") or "")
        if scenario not in SCENARIO_PROFILE_DEFAULTS:
            failures.append(issue("SUMMARY_SCENARIO_INVALID", f"summary.json references unknown scenario: {scenario}", scenario=scenario))
            continue
        if not drop_directory:
            failures.append(issue("SUMMARY_DROP_DIRECTORY_MISSING", f"summary.json scenario has no dropDirectory: {scenario}", scenario=scenario))
            continue
        directory = resolve_inside_intake(intake_dir, drop_directory)
        if directory is None:
            failures.append(
                issue(
                    "SUMMARY_DROP_DIRECTORY_OUTSIDE_INTAKE",
                    f"summary.json dropDirectory escapes intake directory: {drop_directory}",
                    scenario=scenario,
                )
            )
        elif not directory.is_dir():
            failures.append(
                issue("SUMMARY_DROP_DIRECTORY_MISSING", f"summary.json dropDirectory does not exist: {drop_directory}", scenario=scenario)
            )
        elif not (directory / "README.md").exists():
            warnings.append(issue("SCENARIO_README_MISSING", f"Scenario folder has no README.md: {drop_directory}", scenario=scenario))


def verify_manifest_samples(
    intake_dir: Path,
    samples: list[Any],
    failures: list[dict[str, Any]],
    warnings: list[dict[str, Any]],
) -> None:
    seen_slots: set[str] = set()
    referenced_files: dict[str, str] = {}
    for index, raw_item in enumerate(samples):
        if not isinstance(raw_item, dict):
            failures.append(issue("MANIFEST_SAMPLE_INVALID", f"Sample #{index + 1} is not an object."))
            continue
        slot_id = str(raw_item.get("slotId") or f"sample-{index + 1:03d}")
        scenario = str(raw_item.get("scenario") or "")
        if slot_id in seen_slots:
            failures.append(issue("SLOT_ID_DUPLICATE", f"Duplicate slotId: {slot_id}", slotId=slot_id, scenario=scenario))
        seen_slots.add(slot_id)
        if scenario not in SCENARIO_PROFILE_DEFAULTS:
            failures.append(issue("SCENARIO_INVALID", f"Unknown OCR 100 scenario: {scenario}", slotId=slot_id, scenario=scenario))
            continue
        default_profile_id, default_document_type = SCENARIO_PROFILE_DEFAULTS[scenario]
        profile_id = str(raw_item.get("profileId") or "")
        document_type = str(raw_item.get("documentType") or "")
        if profile_id != default_profile_id:
            failures.append(
                issue(
                    "PROFILE_ID_MISMATCH",
                    f"{slot_id} profileId={profile_id!r} does not match {scenario} default {default_profile_id!r}.",
                    slotId=slot_id,
                    scenario=scenario,
                )
            )
        if document_type != default_document_type:
            failures.append(
                issue(
                    "DOCUMENT_TYPE_MISMATCH",
                    f"{slot_id} documentType={document_type!r} does not match {scenario} default {default_document_type!r}.",
                    slotId=slot_id,
                    scenario=scenario,
                )
            )
        file_name = str(raw_item.get("fileName") or "")
        drop_directory = str(raw_item.get("dropDirectory") or "")
        if not drop_directory:
            failures.append(issue("DROP_DIRECTORY_MISSING", f"{slot_id} has no dropDirectory.", slotId=slot_id, scenario=scenario))
            continue
        directory = resolve_inside_intake(intake_dir, drop_directory)
        if directory is None:
            failures.append(
                issue("DROP_DIRECTORY_OUTSIDE_INTAKE", f"{slot_id} dropDirectory escapes intake directory: {drop_directory}", slotId=slot_id, scenario=scenario)
            )
            continue
        if not directory.is_dir():
            failures.append(issue("DROP_DIRECTORY_NOT_FOUND", f"{slot_id} dropDirectory does not exist: {drop_directory}", slotId=slot_id, scenario=scenario))
            continue
        if not file_name:
            failures.append(issue("FILE_NAME_MISSING", f"{slot_id} has no fileName.", slotId=slot_id, scenario=scenario))
            continue
        if is_placeholder(file_name):
            warnings.append(issue("FILE_NAME_PLACEHOLDER", f"{slot_id} still uses placeholder fileName: {file_name}", slotId=slot_id, scenario=scenario))
            continue
        if Path(file_name).name != file_name:
            failures.append(issue("FILE_NAME_NOT_BASENAME", f"{slot_id} fileName must be a basename: {file_name}", slotId=slot_id, scenario=scenario))
            continue
        source_path = (directory / file_name).resolve()
        if source_path.suffix.lower() not in SUPPORTED_SUFFIXES:
            failures.append(issue("FILE_SUFFIX_UNSUPPORTED", f"{slot_id} file suffix is not supported: {file_name}", slotId=slot_id, scenario=scenario))
        if not source_path.exists():
            failures.append(issue("FILE_NOT_FOUND", f"{slot_id} file does not exist: {source_path}", slotId=slot_id, scenario=scenario))
            continue
        if not source_path.is_file():
            failures.append(issue("FILE_NOT_REGULAR", f"{slot_id} path is not a file: {source_path}", slotId=slot_id, scenario=scenario))
            continue
        if source_path.stat().st_size <= 0:
            failures.append(issue("FILE_EMPTY", f"{slot_id} file is empty: {source_path}", slotId=slot_id, scenario=scenario))
        reference_key = str(source_path)
        if reference_key in referenced_files:
            failures.append(
                issue(
                    "FILE_REFERENCE_DUPLICATE",
                    f"{slot_id} references the same file as {referenced_files[reference_key]}: {source_path}",
                    slotId=slot_id,
                    scenario=scenario,
                )
            )
        referenced_files[reference_key] = slot_id


def resolve_inside_intake(intake_dir: Path, value: str) -> Path | None:
    path = Path(value).expanduser()
    candidate = path if path.is_absolute() else intake_dir / path
    try:
        resolved = candidate.resolve()
        resolved.relative_to(intake_dir)
        return resolved
    except Exception:
        return None


def is_placeholder(file_name: str) -> bool:
    return Path(file_name).name.startswith(PLACEHOLDER_PREFIX)


def build_report(
    intake_dir: Path,
    manifest_path: Path,
    samples: list[Any],
    failures: list[dict[str, Any]],
    warnings: list[dict[str, Any]],
    intake_summary: dict[str, Any],
) -> dict[str, Any]:
    scenario_summary: dict[str, dict[str, Any]] = {}
    placeholders = 0
    filled = 0
    for raw_item in samples:
        if not isinstance(raw_item, dict):
            continue
        scenario = str(raw_item.get("scenario") or "unspecified")
        entry = scenario_summary.setdefault(scenario, {"slots": 0, "filled": 0, "placeholders": 0})
        entry["slots"] += 1
        file_name = str(raw_item.get("fileName") or "")
        if file_name and not is_placeholder(file_name):
            filled += 1
            entry["filled"] += 1
        else:
            placeholders += 1
            entry["placeholders"] += 1
    failure_counts = count_codes(failures)
    warning_counts = count_codes(warnings)
    ready_to_ingest = not failures and placeholders == 0 and bool(samples)
    summary = {
        "schemaVersion": "aicheck-ocr-100-collection-intake-verify-v1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "intakeDir": str(intake_dir),
        "manifest": str(manifest_path),
        "slots": len([item for item in samples if isinstance(item, dict)]),
        "filledSlots": filled,
        "placeholderSlots": placeholders,
        "readyToIngest": ready_to_ingest,
        "failureCount": len(failures),
        "warningCount": len(warnings),
        "failureCounts": failure_counts,
        "warningCounts": warning_counts,
        "scenarioSummary": dict(sorted(scenario_summary.items())),
        "sourceSummarySlots": intake_summary.get("slots"),
    }
    if intake_summary.get("slots") is not None and int_or_none(intake_summary.get("slots")) != summary["slots"]:
        warnings.append(
            issue(
                "SUMMARY_SLOT_COUNT_MISMATCH",
                f"summary.json slots={intake_summary.get('slots')} but manifest has {summary['slots']} samples.",
            )
        )
        summary["warningCount"] = len(warnings)
        summary["warningCounts"] = count_codes(warnings)
    return {
        "schemaVersion": "aicheck-ocr-100-collection-intake-verify-v1",
        "ok": not failures,
        "readyToIngest": ready_to_ingest,
        "summary": summary,
        "failures": failures,
        "warnings": warnings,
    }


def issue(code: str, message: str, **extra: Any) -> dict[str, Any]:
    payload = {"code": code, "message": message}
    payload.update({key: value for key, value in extra.items() if value not in {None, ""}})
    return payload


def count_codes(items: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        code = str(item.get("code") or "UNKNOWN")
        counts[code] = counts.get(code, 0) + 1
    return dict(sorted(counts.items()))


def int_or_none(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    lines = [
        "# OCR 100 Collection Intake Verification",
        "",
        f"- Status: {'READY' if report.get('readyToIngest') else 'NOT READY'}",
        f"- Structural OK: {bool(report.get('ok'))}",
        f"- Slots: {summary.get('slots', 0)}",
        f"- Filled slots: {summary.get('filledSlots', 0)}",
        f"- Placeholder slots: {summary.get('placeholderSlots', 0)}",
        f"- Failures: {summary.get('failureCount', 0)}",
        f"- Warnings: {summary.get('warningCount', 0)}",
        "",
        "## Scenario Summary",
        "",
        "| Scenario | Slots | Filled | Placeholders |",
        "| --- | ---: | ---: | ---: |",
    ]
    scenario_summary = summary.get("scenarioSummary") if isinstance(summary.get("scenarioSummary"), dict) else {}
    for scenario, item in scenario_summary.items():
        if not isinstance(item, dict):
            continue
        lines.append(f"| {scenario} | {item.get('slots', 0)} | {item.get('filled', 0)} | {item.get('placeholders', 0)} |")
    if not scenario_summary:
        lines.append("| none | 0 | 0 | 0 |")
    lines.extend(["", "## Failures", ""])
    failures = report.get("failures") if isinstance(report.get("failures"), list) else []
    if failures:
        lines.extend(["| Code | Slot | Scenario | Message |", "| --- | --- | --- | --- |"])
        for item in failures:
            if isinstance(item, dict):
                lines.append(f"| {item.get('code')} | {item.get('slotId', '')} | {item.get('scenario', '')} | {item.get('message')} |")
    else:
        lines.append("No structural failures.")
    lines.extend(["", "## Warnings", ""])
    warnings = report.get("warnings") if isinstance(report.get("warnings"), list) else []
    if warnings:
        lines.extend(["| Code | Slot | Scenario | Message |", "| --- | --- | --- | --- |"])
        for item in warnings:
            if isinstance(item, dict):
                lines.append(f"| {item.get('code')} | {item.get('slotId', '')} | {item.get('scenario', '')} | {item.get('message')} |")
    else:
        lines.append("No warnings.")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
