from __future__ import annotations

import argparse
import csv
import json
import shutil
import subprocess
import sys
from copy import deepcopy
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.ocr_100_corpus import OCR_100_SCENARIO_TARGETS, expected_annotation_checklist
from scripts.ocr_eval_set import write_text_file


def main() -> int:
    parser = argparse.ArgumentParser(description="Build an OCR 100 human annotation work pack from a sample queue.")
    parser.add_argument("queue", help="Sample queue JSON generated by ocr_100_ingest_samples.py.")
    parser.add_argument("--output-dir", required=True, help="Directory where task JSON/CSV/Markdown and previews are written.")
    parser.add_argument("--source-base-dir", default=".", help="Base directory for relative source.path values in the queue.")
    parser.add_argument("--render-previews", action="store_true", help="Render PDF/image previews for annotators when local tools are available.")
    parser.add_argument("--max-pages", type=int, default=2, help="Maximum pages per PDF to render when --render-previews is enabled.")
    parser.add_argument("--preview-max-pixels", type=int, default=1200, help="Maximum long side for rendered image previews.")
    parser.add_argument("--page-level-tasks", action="store_true", help="Split rendered multi-page cases into page-level annotation tasks.")
    args = parser.parse_args()

    pack = build_annotation_pack(
        Path(args.queue),
        output_dir=Path(args.output_dir),
        source_base_dir=Path(args.source_base_dir),
        render_previews=bool(args.render_previews),
        max_pages=max(1, int(args.max_pages)),
        preview_max_pixels=max(100, int(args.preview_max_pixels)),
        page_level_tasks=bool(args.page_level_tasks),
    )
    print(json.dumps(pack["summary"], ensure_ascii=False, indent=2))
    return 0


def build_annotation_pack(
    queue_path: Path,
    *,
    output_dir: Path,
    source_base_dir: Path,
    render_previews: bool = False,
    max_pages: int = 2,
    preview_max_pixels: int = 1200,
    page_level_tasks: bool = False,
) -> dict[str, Any]:
    payload = json.loads(queue_path.expanduser().read_text(encoding="utf-8"))
    cases = payload.get("cases") if isinstance(payload, dict) else payload
    if not isinstance(cases, list):
        raise ValueError("sample queue must be a JSON object with cases[] or a raw case list.")

    output_dir.mkdir(parents=True, exist_ok=True)
    preview_dir = output_dir / "previews"
    source_base_dir = source_base_dir.expanduser().resolve()
    tasks: list[dict[str, Any]] = []
    render_events: list[dict[str, Any]] = []
    for case in cases:
        if not isinstance(case, dict):
            continue
        task = build_task(case, source_base_dir=source_base_dir)
        if render_previews:
            previews, events = render_case_previews(
                task["sourcePathResolved"],
                preview_dir=preview_dir,
                case_id=task["caseId"],
                max_pages=max_pages,
                preview_max_pixels=preview_max_pixels,
            )
            task["previewPaths"] = [relative_to_output(path, output_dir=output_dir) for path in previews]
            task["previewStatus"] = "rendered" if previews else "unavailable"
            task["previewEvents"] = events
            render_events.extend(events)
        else:
            task["previewPaths"] = []
            task["previewStatus"] = "not_requested"
            task["previewEvents"] = []
        if page_level_tasks and task.get("previewPaths"):
            tasks.extend(page_tasks(task))
        else:
            tasks.append(task)

    scenario_counts = count_scenarios(tasks)
    summary = {
        "schemaVersion": "aicheck-ocr-100-annotation-pack-v1",
        "generatedAt": datetime.now(UTC).isoformat(),
        "queue": str(queue_path),
        "tasks": len(tasks),
        "scenarioCounts": scenario_counts,
        "scenarioTargetGapsAfterQueue": scenario_target_gaps(scenario_counts),
        "renderPreviews": bool(render_previews),
        "pageLevelTasks": bool(page_level_tasks),
        "renderedPreviewCount": sum(len(task.get("previewPaths") or []) for task in tasks),
        "renderEventCount": len(render_events),
    }
    pack = {"summary": summary, "tasks": tasks}
    write_text_file(output_dir / "annotation_tasks.json", json.dumps(pack, ensure_ascii=False, indent=2))
    write_text_file(output_dir / "annotation_tasks.csv", tasks_csv(tasks))
    write_text_file(output_dir / "README.md", tasks_markdown(summary, tasks))
    return pack


def build_task(case: dict[str, Any], *, source_base_dir: Path) -> dict[str, Any]:
    source = case.get("source") if isinstance(case.get("source"), dict) else {}
    source_path = str(source.get("path") or "")
    resolved = resolve_source_path(source_path, source_base_dir=source_base_dir)
    scenario = str(case.get("scenario") or "unspecified")
    expected = case.get("expected") if isinstance(case.get("expected"), dict) else {}
    return {
        "taskId": f"label-{case.get('caseId') or 'unknown'}",
        "caseId": case.get("caseId"),
        "scenario": scenario,
        "profileId": case.get("profileId"),
        "documentType": case.get("documentType"),
        "collectionStatus": case.get("collectionStatus"),
        "sourcePath": source_path,
        "sourcePathResolved": str(resolved),
        "fileName": source.get("fileName") or Path(source_path).name,
        "pageCount": source.get("pageCount"),
        "notes": source.get("notes"),
        "classification": source.get("classification"),
        "checklist": expected_annotation_checklist(scenario),
        "expectedTemplate": expected,
        "labelingInstructions": labeling_instructions(expected),
        "certificationBlockers": certification_blockers(expected),
    }


def page_tasks(task: dict[str, Any]) -> list[dict[str, Any]]:
    tasks: list[dict[str, Any]] = []
    previews = [item for item in task.get("previewPaths") or [] if isinstance(item, str) and item.strip()]
    for index, preview_path in enumerate(previews, start=1):
        page_no = page_no_from_preview(preview_path, fallback=index)
        page_task = deepcopy(task)
        page_task["parentTaskId"] = task.get("taskId")
        page_task["taskId"] = f"{task.get('taskId')}-p{page_no}"
        page_task["pageNo"] = page_no
        page_task["pagePreviewPath"] = preview_path
        page_task["previewPaths"] = [preview_path]
        page_task["labelingInstructions"] = [
            *list(task.get("labelingInstructions") or []),
            f"This is page-level task pageNo={page_no}; every bbox/polygon label must keep this pageNo.",
        ]
        tasks.append(page_task)
    return tasks


def page_no_from_preview(value: str, *, fallback: int) -> int:
    name = Path(value).stem
    for marker in ["_p", "-p", "page_"]:
        if marker in name:
            raw = name.rsplit(marker, 1)[-1]
            digits = "".join(char for char in raw if char.isdigit())
            if digits:
                return max(1, int(digits))
    return max(1, int(fallback))


def resolve_source_path(value: str, *, source_base_dir: Path) -> Path:
    path = Path(value).expanduser()
    if path.is_absolute():
        return path
    return (source_base_dir / path).resolve()


def labeling_instructions(expected: dict[str, Any]) -> list[str]:
    instructions = [
        "Replace placeholder values such as replace-with-label with the exact human label.",
        "Replace [0,0,0,0] bbox placeholders with positive-area [x1,y1,x2,y2] coordinates in rendered page pixels.",
        "Use polygon only when bbox cannot tightly represent the evidence region.",
    ]
    if expected.get("fields"):
        instructions.append("For every expected field, label fieldCode, value, pageNo when known, and bbox or polygon.")
    if expected.get("tables"):
        instructions.append("For every expected table, label businessSchema, minRows/minColumns or normalizedRows, and table bbox.")
    if expected.get("seals"):
        instructions.append("For every expected seal, label nameContains or sealType plus seal bbox/polygon.")
    if expected.get("diagnostics"):
        instructions.append("For quality gate cases, label expected diagnostic code and qualityStatus.")
    return instructions


def certification_blockers(expected: dict[str, Any]) -> list[str]:
    blockers: list[str] = []
    raw = json.dumps(expected, ensure_ascii=False)
    if "replace-with-" in raw:
        blockers.append("placeholder_labels")
    if "[0, 0, 0, 0]" in raw or "[0,0,0,0]" in raw:
        blockers.append("zero_area_bbox")
    return blockers


def render_case_previews(
    source_path: str,
    *,
    preview_dir: Path,
    case_id: str,
    max_pages: int,
    preview_max_pixels: int,
) -> tuple[list[Path], list[dict[str, Any]]]:
    path = Path(source_path)
    if not path.exists():
        return [], [{"status": "skipped", "reason": "source_missing", "path": str(path)}]
    suffix = path.suffix.lower()
    if suffix == ".pdf":
        return render_pdf_previews(
            path,
            preview_dir=preview_dir,
            case_id=case_id,
            max_pages=max_pages,
            preview_max_pixels=preview_max_pixels,
        )
    if suffix in {".heic", ".heif"}:
        return render_heic_preview(path, preview_dir=preview_dir, case_id=case_id, preview_max_pixels=preview_max_pixels)
    if suffix in {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}:
        preview_dir.mkdir(parents=True, exist_ok=True)
        target = preview_dir / f"{safe_name(case_id)}_image{suffix if suffix != '.jpeg' else '.jpg'}"
        if not target.exists():
            shutil.copy2(path, target)
        return [target], [{"status": "rendered", "engine": "copy", "path": str(target)}]
    return [], [{"status": "skipped", "reason": "unsupported_suffix", "path": str(path)}]


def render_pdf_previews(
    path: Path,
    *,
    preview_dir: Path,
    case_id: str,
    max_pages: int,
    preview_max_pixels: int,
) -> tuple[list[Path], list[dict[str, Any]]]:
    try:
        import fitz  # type: ignore
    except Exception as exc:
        previews = existing_pdf_previews(preview_dir=preview_dir, case_id=case_id, max_pages=max_pages)
        if previews:
            return previews, [
                {
                    "status": "rendered",
                    "engine": "reuse-existing",
                    "reason": "pymupdf_unavailable",
                    "detail": exc.__class__.__name__,
                    "path": str(path),
                }
                for path in previews
            ]
        return [], [{"status": "skipped", "reason": "pymupdf_unavailable", "detail": exc.__class__.__name__}]
    previews: list[Path] = []
    events: list[dict[str, Any]] = []
    preview_dir.mkdir(parents=True, exist_ok=True)
    try:
        with fitz.open(path) as document:
            for page_index in range(min(max_pages, int(document.page_count))):
                page = document[page_index]
                scale = preview_scale(page.rect.width, page.rect.height, preview_max_pixels=preview_max_pixels)
                pixmap = page.get_pixmap(matrix=fitz.Matrix(scale, scale), alpha=False)
                target = preview_dir / f"{safe_name(case_id)}_p{page_index + 1}.png"
                pixmap.save(target)
                previews.append(target)
                events.append({"status": "rendered", "engine": "pymupdf", "page": page_index + 1, "path": str(target)})
    except Exception as exc:
        return previews, [*events, {"status": "failed", "engine": "pymupdf", "reason": exc.__class__.__name__}]
    return previews, events


def existing_pdf_previews(*, preview_dir: Path, case_id: str, max_pages: int) -> list[Path]:
    safe_case_id = safe_name(case_id)
    previews = [
        preview_dir / f"{safe_case_id}_p{page_index}.png"
        for page_index in range(1, max_pages + 1)
        if (preview_dir / f"{safe_case_id}_p{page_index}.png").exists()
    ]
    return previews


def render_heic_preview(
    path: Path,
    *,
    preview_dir: Path,
    case_id: str,
    preview_max_pixels: int,
) -> tuple[list[Path], list[dict[str, Any]]]:
    sips = shutil.which("sips")
    if not sips:
        return [], [{"status": "skipped", "reason": "sips_unavailable", "path": str(path)}]
    preview_dir.mkdir(parents=True, exist_ok=True)
    target = preview_dir / f"{safe_name(case_id)}_image.png"
    command = [sips, "-s", "format", "png", "-Z", str(preview_max_pixels), str(path), "--out", str(target)]
    completed = subprocess.run(command, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if completed.returncode != 0:
        return [], [{"status": "failed", "engine": "sips", "reason": completed.stderr.strip()[:200], "path": str(path)}]
    return [target], [{"status": "rendered", "engine": "sips", "path": str(target)}]


def preview_scale(width: float, height: float, *, preview_max_pixels: int) -> float:
    long_side = max(float(width or 1), float(height or 1))
    return max(0.1, min(4.0, float(preview_max_pixels) / long_side))


def tasks_csv(tasks: list[dict[str, Any]]) -> str:
    from io import StringIO

    handle = StringIO()
    fieldnames = [
        "caseId",
        "scenario",
        "profileId",
        "documentType",
        "fileName",
        "pageNo",
        "sourcePath",
        "pageCount",
        "collectionStatus",
        "certificationBlockers",
        "checklist",
        "notes",
    ]
    writer = csv.DictWriter(handle, fieldnames=fieldnames)
    writer.writeheader()
    for task in tasks:
        writer.writerow(
            {
                "caseId": task.get("caseId"),
                "scenario": task.get("scenario"),
                "profileId": task.get("profileId"),
                "documentType": task.get("documentType"),
                "fileName": task.get("fileName"),
                "pageNo": task.get("pageNo"),
                "sourcePath": task.get("sourcePath"),
                "pageCount": task.get("pageCount"),
                "collectionStatus": task.get("collectionStatus"),
                "certificationBlockers": ";".join(task.get("certificationBlockers") or []),
                "checklist": "; ".join(task.get("checklist") or []),
                "notes": task.get("notes") or "",
            }
        )
    return handle.getvalue()


def tasks_markdown(summary: dict[str, Any], tasks: list[dict[str, Any]]) -> str:
    lines = [
        "# AIcheck OCR 100 Annotation Pack",
        "",
        f"- Generated: {summary['generatedAt']}",
        f"- Tasks: {summary['tasks']}",
        f"- Rendered previews: {summary['renderedPreviewCount']}",
        "",
        "## Scenario Counts",
        "",
        "| Scenario | Queue Cases | Target | Remaining Target Gap |",
        "| --- | ---: | ---: | ---: |",
    ]
    counts = summary.get("scenarioCounts") or {}
    gaps = summary.get("scenarioTargetGapsAfterQueue") or {}
    for scenario, target in OCR_100_SCENARIO_TARGETS.items():
        lines.append(f"| {scenario} | {counts.get(scenario, 0)} | {target} | {gaps.get(scenario, target)} |")
    lines.extend(["", "## Tasks", ""])
    for task in tasks:
        lines.extend(
            [
                f"### {task.get('caseId')} - {task.get('scenario')}",
                "",
                f"- File: `{task.get('sourcePath')}`",
                f"- Profile: `{task.get('profileId')}`",
                f"- Status: `{task.get('collectionStatus')}`",
                f"- Blockers: `{', '.join(task.get('certificationBlockers') or ['none'])}`",
            ]
        )
        if task.get("previewPaths"):
            lines.append("- Previews: " + ", ".join(f"[{Path(path).name}]({path})" for path in task["previewPaths"]))
        if task.get("notes"):
            lines.append(f"- Notes: {task['notes']}")
        lines.append("- Checklist: " + "; ".join(task.get("checklist") or []))
        lines.append("")
    return "\n".join(lines)


def count_scenarios(tasks: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for task in tasks:
        scenario = str(task.get("scenario") or "unspecified")
        counts[scenario] = counts.get(scenario, 0) + 1
    return dict(sorted(counts.items()))


def scenario_target_gaps(scenario_counts: dict[str, int]) -> dict[str, int]:
    return {
        scenario: max(0, target - int(scenario_counts.get(scenario, 0)))
        for scenario, target in OCR_100_SCENARIO_TARGETS.items()
    }


def safe_name(value: Any) -> str:
    return "".join(char if char.isalnum() or char in {"-", "_"} else "_" for char in str(value)).strip("_") or "task"


def relative_to_output(path: Path, *, output_dir: Path) -> str:
    try:
        return str(path.resolve().relative_to(output_dir.resolve()))
    except ValueError:
        return str(path.resolve())


if __name__ == "__main__":
    raise SystemExit(main())
