from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.ocr_100_annotation_pack import build_annotation_pack
from scripts.ocr_100_annotation_prelabel import prelabel_annotation_tasks
from scripts.ocr_100_collection_intake_autofill import autofill_collection_intake
from scripts.ocr_100_collection_intake_verify import verify_collection_intake
from scripts.ocr_100_ingest_samples import build_sample_queue, load_manifest
from scripts.ocr_eval_set import write_text_file


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the OCR 100 sample intake pipeline with explicit readiness gates.")
    parser.add_argument("intake_dir", help="Directory generated by ocr_100_collection_intake.py.")
    parser.add_argument("--manifest", default="manifest_template.json", help="Input manifest path, relative to intake_dir unless absolute.")
    parser.add_argument("--autofilled-manifest", default="manifest_autofilled.json", help="Autofilled manifest output path, relative to intake_dir unless absolute.")
    parser.add_argument("--queue-output", default="ocr_eval/reports/new_sample_queue.json")
    parser.add_argument("--annotation-output-dir", default="ocr_eval/reports/new_annotation_pack")
    parser.add_argument("--ocr-result-dir", default="ocr_eval/reports/new_ocr_results")
    parser.add_argument("--base-dir", default=".")
    parser.add_argument("--copy-to", default="ocr_eval/real_samples")
    parser.add_argument("--execute", action="store_true", help="Actually ingest samples and build annotation pack after verification passes.")
    parser.add_argument("--render-previews", action="store_true", help="Render annotation previews when building the pack.")
    parser.add_argument("--run-prelabel", action="store_true", help="Run OCR prelabel after building the annotation pack.")
    parser.add_argument("--auto-discover-runtime", action="store_true", help="Apply runtime discovery for OCR prelabeling.")
    parser.add_argument("--include-standards", action="store_true", help="Allow likely standards/specification PDFs in autofill/ingest.")
    parser.add_argument("--strict", action="store_true", help="Return non-zero unless the pipeline reaches an executable state.")
    parser.add_argument("--output", help="Optional JSON report path.")
    parser.add_argument("--markdown-output", help="Optional Markdown report path.")
    args = parser.parse_args()

    report = run_collection_pipeline(
        Path(args.intake_dir),
        manifest=Path(args.manifest),
        autofilled_manifest=Path(args.autofilled_manifest),
        queue_output=Path(args.queue_output),
        annotation_output_dir=Path(args.annotation_output_dir),
        ocr_result_dir=Path(args.ocr_result_dir),
        base_dir=Path(args.base_dir),
        copy_to=Path(args.copy_to),
        execute=bool(args.execute),
        render_previews=bool(args.render_previews),
        run_prelabel=bool(args.run_prelabel),
        auto_discover_runtime=bool(args.auto_discover_runtime),
        include_standards=bool(args.include_standards),
    )
    if args.output:
        write_text_file(Path(args.output), json.dumps(report, ensure_ascii=False, indent=2))
    if args.markdown_output:
        write_text_file(Path(args.markdown_output), markdown_report(report))
    print(json.dumps(report["summary"], ensure_ascii=False, indent=2))
    if args.strict:
        return 0 if report.get("readyToExecute") else 1
    return 0 if report.get("ok") else 1


def run_collection_pipeline(
    intake_dir: Path,
    *,
    manifest: Path | None = None,
    autofilled_manifest: Path | None = None,
    queue_output: Path,
    annotation_output_dir: Path,
    ocr_result_dir: Path,
    base_dir: Path,
    copy_to: Path,
    execute: bool = False,
    render_previews: bool = False,
    run_prelabel: bool = False,
    auto_discover_runtime: bool = False,
    include_standards: bool = False,
) -> dict[str, Any]:
    intake_dir = intake_dir.expanduser().resolve()
    manifest = manifest or Path("manifest_template.json")
    autofilled_manifest = autofilled_manifest or Path("manifest_autofilled.json")
    output_manifest_path = resolve_output_manifest(intake_dir, autofilled_manifest)
    autofill = autofill_collection_intake(
        intake_dir,
        manifest=manifest,
        output_manifest=output_manifest_path,
        include_standards=include_standards,
    )
    verification = verify_collection_intake(intake_dir, manifest=output_manifest_path)
    ready = bool(verification.get("readyToIngest"))
    planned_steps = planned_pipeline_steps(
        intake_dir=intake_dir,
        manifest_path=output_manifest_path,
        queue_output=queue_output,
        annotation_output_dir=annotation_output_dir,
        ocr_result_dir=ocr_result_dir,
        base_dir=base_dir,
        copy_to=copy_to,
        render_previews=render_previews,
        run_prelabel=run_prelabel,
        auto_discover_runtime=auto_discover_runtime,
    )
    executed_steps: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []
    if execute and ready:
        try:
            executed_steps.extend(
                execute_ready_pipeline(
                    intake_dir=intake_dir,
                    manifest_path=output_manifest_path,
                    queue_output=queue_output,
                    annotation_output_dir=annotation_output_dir,
                    ocr_result_dir=ocr_result_dir,
                    base_dir=base_dir,
                    copy_to=copy_to,
                    render_previews=render_previews,
                    run_prelabel=run_prelabel,
                    auto_discover_runtime=auto_discover_runtime,
                    include_standards=include_standards,
                )
            )
        except Exception as exc:
            failures.append({"code": "PIPELINE_EXECUTION_FAILED", "message": str(exc)})
    elif execute and not ready:
        executed_steps.append({"step": "execute", "status": "skipped", "reason": "intake_not_ready"})

    summary = {
        "schemaVersion": "aicheck-ocr-100-collection-intake-pipeline-v1",
        "generatedAt": datetime.now(UTC).isoformat(),
        "intakeDir": str(intake_dir),
        "execute": bool(execute),
        "readyToExecute": ready and not failures,
        "autofilledManifest": str(output_manifest_path),
        "queueOutput": str(queue_output),
        "annotationOutputDir": str(annotation_output_dir),
        "assignedSlots": autofill.get("summary", {}).get("assignedSlots"),
        "placeholderSlots": verification.get("summary", {}).get("placeholderSlots"),
        "filledSlots": verification.get("summary", {}).get("filledSlots"),
        "verificationFailures": verification.get("summary", {}).get("failureCount"),
        "verificationWarnings": verification.get("summary", {}).get("warningCount"),
        "plannedSteps": len(planned_steps),
        "executedSteps": len(executed_steps),
        "failureCount": len(failures),
    }
    return {
        "schemaVersion": "aicheck-ocr-100-collection-intake-pipeline-v1",
        "ok": not failures,
        "readyToExecute": ready and not failures,
        "summary": summary,
        "autofill": autofill,
        "verification": verification,
        "plannedSteps": planned_steps,
        "executedSteps": executed_steps,
        "failures": failures,
    }


def resolve_output_manifest(intake_dir: Path, value: Path) -> Path:
    value = value.expanduser()
    if value.is_absolute():
        return value.resolve()
    return (intake_dir / value).resolve()


def planned_pipeline_steps(
    *,
    intake_dir: Path,
    manifest_path: Path,
    queue_output: Path,
    annotation_output_dir: Path,
    ocr_result_dir: Path,
    base_dir: Path,
    copy_to: Path,
    render_previews: bool,
    run_prelabel: bool,
    auto_discover_runtime: bool,
) -> list[dict[str, Any]]:
    samples_dir = intake_dir / "samples"
    steps = [
        {
            "step": "ingest",
            "command": (
                f"python scripts/ocr_100_ingest_samples.py {samples_dir} "
                f"--manifest {manifest_path} --base-dir {base_dir} --copy-to {copy_to} --output {queue_output}"
            ),
        },
        {
            "step": "annotation_pack",
            "command": (
                f"python scripts/ocr_100_annotation_pack.py {queue_output} --output-dir {annotation_output_dir}"
                + (" --render-previews" if render_previews else "")
            ),
        },
    ]
    if run_prelabel:
        steps.append(
            {
                "step": "prelabel",
                "command": (
                    f"python scripts/ocr_100_annotation_prelabel.py {annotation_output_dir / 'annotation_tasks.json'} "
                    f"--output {annotation_output_dir / 'prelabelled_tasks.json'} "
                    f"--source-base-dir {base_dir} --run-ocr --save-result-dir {ocr_result_dir}"
                    + (" --auto-discover-runtime" if auto_discover_runtime else "")
                ),
            }
        )
    return steps


def execute_ready_pipeline(
    *,
    intake_dir: Path,
    manifest_path: Path,
    queue_output: Path,
    annotation_output_dir: Path,
    ocr_result_dir: Path,
    base_dir: Path,
    copy_to: Path,
    render_previews: bool,
    run_prelabel: bool,
    auto_discover_runtime: bool,
    include_standards: bool,
) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []
    samples_dir = intake_dir / "samples"
    queue = build_sample_queue(
        [samples_dir],
        base_dir=base_dir,
        copy_to=copy_to,
        manifest=load_manifest(manifest_path),
        include_standards=include_standards,
    )
    write_text_file(queue_output, json.dumps(queue, ensure_ascii=False, indent=2))
    steps.append({"step": "ingest", "status": "done", "output": str(queue_output), "cases": len(queue.get("cases") or [])})

    pack = build_annotation_pack(
        queue_output,
        output_dir=annotation_output_dir,
        source_base_dir=base_dir,
        render_previews=render_previews,
    )
    steps.append(
        {
            "step": "annotation_pack",
            "status": "done",
            "output": str(annotation_output_dir / "annotation_tasks.json"),
            "tasks": pack.get("summary", {}).get("tasks"),
        }
    )
    if run_prelabel:
        if auto_discover_runtime:
            from scripts.ocr_100_annotation_prelabel import apply_auto_discovered_runtime

            apply_auto_discovered_runtime()
        prelabel = prelabel_annotation_tasks(
            annotation_output_dir / "annotation_tasks.json",
            output_path=annotation_output_dir / "prelabelled_tasks.json",
            source_base_dir=base_dir,
            save_result_dir=ocr_result_dir,
            run_ocr=True,
        )
        steps.append(
            {
                "step": "prelabel",
                "status": "done" if prelabel.get("ok") else "failed",
                "output": str(annotation_output_dir / "prelabelled_tasks.json"),
                "tasks": prelabel.get("summary", {}).get("tasks"),
            }
        )
    return steps


def markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    lines = [
        "# OCR 100 Collection Intake Pipeline",
        "",
        f"- Status: {'READY' if report.get('readyToExecute') else 'NOT READY'}",
        f"- Execute requested: {summary.get('execute')}",
        f"- Assigned slots: {summary.get('assignedSlots')}",
        f"- Filled slots: {summary.get('filledSlots')}",
        f"- Placeholder slots: {summary.get('placeholderSlots')}",
        f"- Verification failures: {summary.get('verificationFailures')}",
        f"- Verification warnings: {summary.get('verificationWarnings')}",
        "",
        "## Planned Steps",
        "",
        "| Step | Command |",
        "| --- | --- |",
    ]
    for step in report.get("plannedSteps") or []:
        if isinstance(step, dict):
            lines.append(f"| {step.get('step')} | `{step.get('command')}` |")
    lines.extend(["", "## Executed Steps", ""])
    executed = report.get("executedSteps") if isinstance(report.get("executedSteps"), list) else []
    if executed:
        lines.extend(["| Step | Status | Detail |", "| --- | --- | --- |"])
        for step in executed:
            if isinstance(step, dict):
                detail = step.get("reason") or step.get("output") or ""
                lines.append(f"| {step.get('step')} | {step.get('status')} | {detail} |")
    else:
        lines.append("No execution performed.")
    failures = report.get("failures") if isinstance(report.get("failures"), list) else []
    lines.extend(["", "## Failures", ""])
    if failures:
        lines.extend(["| Code | Message |", "| --- | --- |"])
        for failure in failures:
            if isinstance(failure, dict):
                lines.append(f"| {failure.get('code')} | {failure.get('message')} |")
    else:
        lines.append("No pipeline failures.")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
