from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
ENTRYPOINT_PATH = ROOT / "openapi" / "aicheck.yaml"
INDEX_PATH = ROOT / "openapi" / "contract-index.json"
FRONTEND_OPERATION_MAP_PATH = ROOT / "frontend" / "src" / "api" / "aicheck" / "generated" / "operation-map.ts"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head", "trace"}


def _json_pointer(document: Any, pointer: str) -> Any:
    current = document
    for raw_part in pointer.lstrip("/").split("/"):
        if not raw_part:
            continue
        part = raw_part.replace("~1", "/").replace("~0", "~")
        current = current[int(part)] if isinstance(current, list) else current[part]
    return current


def _resolve_path_item(reference: str) -> dict[str, Any]:
    file_name, _, pointer = reference.partition("#")
    source = ENTRYPOINT_PATH.parent / file_name
    document = yaml.safe_load(source.read_text(encoding="utf-8"))
    resolved = _json_pointer(document, pointer)
    if not isinstance(resolved, dict):
        raise ValueError(f"OpenAPI path reference does not resolve to an object: {reference}")
    return resolved


def build_contract_index() -> dict[str, Any]:
    entrypoint = yaml.safe_load(ENTRYPOINT_PATH.read_text(encoding="utf-8"))
    paths = entrypoint.get("paths") if isinstance(entrypoint, dict) else None
    if not isinstance(paths, dict):
        raise ValueError("OpenAPI entrypoint is missing a paths object")

    operations: list[dict[str, Any]] = []
    seen_operation_ids: set[str] = set()
    for path in sorted(paths):
        path_item = paths[path]
        if not isinstance(path_item, dict):
            continue
        if "$ref" in path_item:
            path_item = _resolve_path_item(str(path_item["$ref"]))
        for method in sorted(HTTP_METHODS & set(path_item)):
            operation = path_item[method]
            if not isinstance(operation, dict) or not operation.get("operationId"):
                continue
            operation_id = str(operation["operationId"])
            if operation_id in seen_operation_ids:
                raise ValueError(f"Duplicate operationId: {operation_id}")
            seen_operation_ids.add(operation_id)
            operations.append(
                {
                    "operationId": operation_id,
                    "method": method.upper(),
                    "path": path,
                    "tags": [str(tag) for tag in operation.get("tags") or []],
                }
            )

    return {
        "entrypoint": "openapi/aicheck.yaml",
        "operationCount": len(operations),
        "operations": operations,
        "codegenTargets": [
            {
                "name": "frontend-aicheck-client",
                "source": "openapi/aicheck.yaml",
                "target": "frontend/src/api/aicheck/generated/operation-map.ts",
                "recommendedGenerator": (
                    "scripts/openapi_contract.py --write-frontend; "
                    "orval/openapi-typescript can replace this map later"
                ),
            }
        ],
    }


def render_frontend_operation_map(index: dict[str, Any]) -> str:
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/openapi_contract.py --write-frontend.",
        "// Do not edit by hand.",
        "",
        "export const aicheckOpenApiOperations = {",
    ]
    operations = index["operations"]
    for position, operation in enumerate(operations):
        operation_id = json.dumps(operation["operationId"], ensure_ascii=False)
        method = json.dumps(operation["method"], ensure_ascii=False)
        path = json.dumps(operation["path"], ensure_ascii=False)
        tags = json.dumps(operation["tags"], ensure_ascii=False)
        suffix = "," if position < len(operations) - 1 else ""
        lines.append(f"  {operation_id}: {{ method: {method}, path: {path}, tags: {tags} }}{suffix}")
    lines.extend(
        [
            "} as const",
            "",
            "export type AicheckOpenApiOperationId = keyof typeof aicheckOpenApiOperations",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and verify AIcheck OpenAPI contract artifacts.")
    parser.add_argument("--write-index", action="store_true")
    parser.add_argument("--write-frontend", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    index = build_contract_index()
    frontend = render_frontend_operation_map(index)
    if args.write_index:
        INDEX_PATH.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.write_frontend:
        FRONTEND_OPERATION_MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
        FRONTEND_OPERATION_MAP_PATH.write_text(frontend, encoding="utf-8")
    if args.check:
        stored_index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
        stored_frontend = FRONTEND_OPERATION_MAP_PATH.read_text(encoding="utf-8")
        if stored_index != index or stored_frontend != frontend:
            return 1
    if not (args.write_index or args.write_frontend or args.check):
        print(json.dumps(index, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
