"""Build the remote tool contract from the maintained portable client schemas."""
from pathlib import Path
import sys, json, inspect, copy
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'skills/aicheck-data-services/scripts'))
from data_client import ACTIONS
from mcp_server import validate
specs=copy.deepcopy(ACTIONS)
specs['ocr_submit']['description']='创建临时上传地址，不读取本机或服务器文件。宿主须使用文件工具将用户指定原件以 PUT 二进制上传到返回的 uploadUrl，再从上传响应取得 jobId。不能只传本机路径或虚构已上传。原件发往本服务和 MinerU 并按服务器策略留存。'
specs['ocr_submit']['inputSchema']={'type':'object','properties':{'fileName':{'type':'string','minLength':1,'maxLength':200},'requestId':{'type':'string','minLength':16,'maxLength':80},'language':{'type':'string','enum':['ch','en']}},'required':['fileName','requestId'],'additionalProperties':False}
specs['ocr_submit']['inputSchema']['properties']['profileId']={'type':'string','minLength':1,'maxLength':100,'description':'可选资料类型；从 connection.ocr.profiles 选择。不明确时省略，由 OCR 文本路由。'}
specs['ocr_result']['description']='读取服务器最终加工的 OCR 结果：资料类型、字段、表格、印章、质量和处理来源。pageNo 过滤页内对象，documentFields 保留未绑定页码的文档级字段；质量与处理信息为全文级。不是 MinerU 原始输出，也不证明工程符合或证件真实。'
specs['connection']['description']='检查远程数据服务能力，不代表 OCR 执行或官方登记查询已完成。'
p=root/'backend/libs/data_service_mcp_contract.py'
p.write_text('"""Generated by scripts/sync_remote_mcp_contract.py; no local-file tools."""\nimport json\n\nACTIONS = '+repr(specs)+'\n\n'+inspect.getsource(validate))
print(p)
